# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Tabulate Events
#' 
#' Tabulate the number at risk and the number of events at each unique
#' observation time.
#' 
#' @param time Event time.
#' @param status Status, coded as 0 for censoring, 1 for an event, 2 for death.
#' @return Data.frame with the censorings, deaths, and events occurring
#'   at each distinct time point. 
#' @export
TabulateEvents <- function(time, status) {
    .Call('_CICs_TabulateEvents', PACKAGE = 'CICs', time, status)
}

#' Calculate CIC
#' 
#' @param time Observation time.
#' @param status Event status. The event coded as 1 is assumed to be the event
#'   of interest.
#' @return Tabulate cumulative incidence curve. 
#' @export 
CalcCIC <- function(time, status) {
    .Call('_CICs_CalcCIC', PACKAGE = 'CICs', time, status)
}

