# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Tabulate Events
#' 
#' Tabulate the number at risk and the number of events at each unique
#' observation time.
#' 
#' @param status Status, coded as 0 for censoring, 1 for an event, 2 for death.
#' @param time Event time.
#' @return Data.frame with the censorings, deaths, and events occurring
#'   at each distinct time point. 
#' @export
TabulateEvents <- function(status, time) {
    .Call(`_CICs_TabulateEvents`, status, time)
}

#' Calculate CIC
#' 
#' @param status Status, coded as 0 for censoring, 1 for an event, 2 for death.
#' @param time Observation time.
#' @return Tabulate cumulative incidence curve. 
#' @export 
CalcCIC <- function(status, time) {
    .Call(`_CICs_CalcCIC`, status, time)
}

#' Influence CIC
#' 
#' @param status Status, coded as 0 for censoring, 1 for an event, 2 for death.
#' @param time Observation time.
#' @param trunc_time Time at which to evaluate the influence function.
#' @return Tabulate cumulative incidence curve. 
#' @export 
InfluenceCIC <- function(status, time, trunc_time) {
    .Call(`_CICs_InfluenceCIC`, status, time, trunc_time)
}

